apiVersion: apps/v1
kind: Deployment

metadata:
  name: firstdeploy
  labels:
    name: firstDeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-slave
  template:
     metadata:
        name: jnlp
        labels:
          app: jenkins-slave
     spec:
      containers:
        - name: mysamplecontainer
          image: shekharsinha/my_repo123:v1_sample
          resources:
            requests:
              memory: 500Mi
          
     
