FROM  openjdk:8u121-jdk-alpine
	RUN apk add --no-cache --virtual=build-dependencies \
      ca-certificates \
      gnupg \
      tar \
      wget \
	  curl \
      lxc \
      iptables
    
# Install Docker from Docker Inc. repositories.
RUN curl -sSL https://get.docker.com/ | sh

# Install the magic wrapper.
ADD ./wrapdocker /usr/local/bin/wrapdocker
RUN chmod +x /usr/local/bin/wrapdocker

# Define additional metadata for our image.
VOLUME /var/lib/docker
CMD ["wrapdocker"]